# Generated by Django 5.1.2 on 2025-07-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PNRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=10, unique=True)),
                ('train_number', models.CharField(max_length=10)),
                ('train_name', models.CharField(max_length=100)),
                ('source_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('source_station_code', models.CharField(max_length=10)),
                ('destination_station_code', models.CharField(max_length=10)),
                ('journey_date', models.DateField()),
                ('passenger_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=10, unique=True)),
                ('station_name', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=10)),
                ('train_number', models.CharField(max_length=10)),
                ('train_name', models.CharField(max_length=100)),
                ('source_station', models.CharField(max_length=100)),
                ('destination_station', models.CharField(max_length=100)),
                ('source_station_code', models.CharField(max_length=10)),
                ('destination_station_code', models.CharField(max_length=10)),
                ('journey_date', models.DateField()),
                ('seat_type', models.CharField(choices=[('LOWER', 'Lower'), ('MIDDLE', 'Middle'), ('UPPER', 'Upper'), ('SIDE_LOWER', 'Side Lower'), ('SIDE_UPPER', 'Side Upper')], max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('coach_number', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_pnr', models.CharField(max_length=10)),
                ('exchange_date', models.DateTimeField(auto_now_add=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_sales', to=settings.AUTH_USER_MODEL)),
                ('seat_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seats.seatlisting')),
            ],
            options={
                'ordering': ['-exchange_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
