# Generated by Django 5.1.2 on 2025-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnrstatus',
            name='travel_class',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
