# Generated by Django 5.1.2 on 2025-07-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_pnrstatus_travel_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_serial_number', models.IntegerField()),
                ('booking_status', models.CharField(max_length=20)),
                ('booking_coach_id', models.CharField(max_length=10)),
                ('booking_berth_no', models.IntegerField()),
                ('booking_berth_code', models.CharField(max_length=10)),
                ('current_status', models.CharField(max_length=20)),
                ('current_coach_id', models.CharField(max_length=10)),
                ('current_berth_no', models.IntegerField()),
                ('current_berth_code', models.CharField(max_length=10)),
                ('pnr_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='seats.pnrstatus')),
            ],
            options={
                'ordering': ['passenger_serial_number'],
            },
        ),
    ]
